# Generated by Django 2.1.5 on 2020-03-06 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Customer')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of the Customer')),
                ('cell', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Must be number', regex='^[0-9]*$')], verbose_name='Contact Number')),
                ('address', models.TextField(max_length=300, verbose_name='Shipping Address')),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
