# Generated by Django 2.1.5 on 2020-04-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('paper_material', models.CharField(max_length=50, verbose_name='Paper material')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Height (in inch)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Width (in inch)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Length (in inch)')),
                ('color_number', models.IntegerField(verbose_name='Number of Printer Colors')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Shipping Charge')),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Vat (Percent)')),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax (Percent)')),
                ('advance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Advance Payment')),
                ('later_payment', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='To be paid later')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Unit Price (BDT)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='product',
            field=models.ManyToManyField(through='erp.QuotationProduct', to='erp.Product'),
        ),
    ]
