# Generated by Django 2.2.12 on 2020-04-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200420_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='advance_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Advance Payment (percent)'),
        ),
    ]
